# Generated by Django 4.2.5 on 2023-10-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dia_cursado', models.CharField(max_length=50)),
                ('descripcion', models.FileField(upload_to='')),
                ('fecha_parcial', models.DateTimeField()),
            ],
        ),
    ]
