# Generated by Django 4.2.5 on 2023-10-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='materia',
            name='fecha_parcial',
            field=models.DateField(),
        ),
    ]
