# Generated by Django 4.2.5 on 2023-10-13 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0002_alter_materia_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
