# Generated by Django 4.2.5 on 2023-11-07 03:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_infoextra_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
