# Generated by Django 4.2.5 on 2023-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_profesor_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
