# Generated by Django 4.2.5 on 2023-10-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_profesor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nac',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
