# Generated by Django 4.2.5 on 2023-10-19 00:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_profesor_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='historial',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
